addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.3.0")
addSbtPlugin("org.foundweekends"  % "sbt-bintray"              % "0.5.6")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "1.6.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.0.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
